//
//  ClaudeMdGenerator.swift
//  StrategyForge
//
//  Generates / updates the repo-root CLAUDE.md. The StrategyForge-owned content
//  lives inside a marked section so an existing CLAUDE.md is never clobbered —
//  only the delimited block is inserted or replaced (idempotent).
//

import Foundation

enum ClaudeMdGenerator {

    static let startMarker = "<!-- CORAL:START -->"
    static let endMarker = "<!-- CORAL:END -->"
    /// Legacy markers from the app's former name. Still recognized when merging so
    /// an already-generated CLAUDE.md gets its block replaced (and upgraded to the
    /// new markers) instead of appending a duplicate.
    static let legacyStartMarker = "<!-- STRATEGYFORGE:START -->"
    static let legacyEndMarker = "<!-- STRATEGYFORGE:END -->"
    static let fileName = "CLAUDE.md"

    // MARK: - Section content

    /// The StrategyForge-managed section (WITHOUT the markers). This is the part
    /// that gets regenerated on every write.
    static func section(for strategy: Strategy, binary: String = "claude") -> String {
        let orchestrator = strategy.orchestrator
        let orchestratorName = orchestrator?.name ?? "orchestrator"
        let orchestratorModel = orchestrator?.model.displayName ?? "—"
        let orchestratorModelID = orchestrator?.model.rawValue ?? "—"

        var out = ""
        out += "# Multi-agent strategy: \(strategy.name)\n\n"
        out += "\(strategy.description)\n\n"
        out += "> Generated by Coral. This section is managed automatically; "
        out += "edit outside the markers to keep your changes.\n\n"

        // Orchestrator
        out += "## Orchestrator\n\n"
        out += "The orchestrator is the **main Claude Code session** (`\(orchestratorName)`). "
        out += "Its model is **not** set in a file — it is chosen at launch.\n\n"
        out += "- Suggested model: **\(orchestratorModel)** (`\(orchestratorModelID)`)\n\n"
        out += "\(LaunchCommandGenerator.instructions(for: strategy, binary: binary))\n\n"

        // Orchestration instructions
        out += "## How to orchestrate\n\n"
        out += "\(strategy.orchestrationNotes)\n\n"

        // Subagents table
        let subagents = strategy.subagentRoles
        if subagents.isEmpty {
            out += "## Subagents\n\n"
            out += "_None — this is a solo configuration with no delegation._\n\n"
        } else {
            out += "## Available subagents\n\n"
            out += "| Subagent | Role | Model | When to use |\n"
            out += "|---|---|---|---|\n"
            var subagentTypes: [String] = []
            for role in subagents {
                let count = max(role.count, 1)
                let nameCell: String
                if count == 1 {
                    nameCell = "`\(role.name)`"
                    subagentTypes.append(role.name)
                } else {
                    nameCell = "`\(role.name)-1`…`\(role.name)-\(count)`"
                    subagentTypes.append(contentsOf: (1...count).map { "\(role.name)-\($0)" })
                }
                let when = role.description
                    .replacingOccurrences(of: "\n", with: " ")
                    .replacingOccurrences(of: "|", with: "\\|")
                out += "| \(nameCell) | \(role.role.displayName) | \(role.model.displayName) | \(when) |\n"
            }
            out += "\n"

            // The delegation is the whole point — and the model will NOT delegate
            // unless told to use the Task tool explicitly. Make it a hard rule and
            // name the exact `subagent_type` values it may call.
            let names = subagentTypes.map { "`\($0)`" }.joined(separator: ", ")
            out += "## Delegate with the Task tool (required)\n\n"
            out += "You are the orchestrator. **Do the work by DELEGATING, not by doing it all yourself.** "
            out += "For anything that fits a subagent above, you MUST call the **Task tool**:\n\n"
            out += "```\nTask(subagent_type: \"\(subagentTypes.first ?? "worker")\", "
            out += "description: \"a precise, self-contained brief with scope + acceptance criteria\")\n```\n\n"
            out += "- Available `subagent_type` values: \(names).\n"
            out += "- When work is parallelizable, launch several subagents **in the same turn** "
            out += "(multiple Task calls at once) so they run concurrently.\n"
            out += "- Give each a complete brief — subagents can't see the conversation, each other, "
            out += "or delegate further.\n"
            out += "- Then collect their reports, integrate, resolve conflicts, and verify.\n"
            out += "- Only skip delegation for trivial one-line answers that need no real work.\n\n"
        }

        // Working agreement — Anthropic's tested prompt guidance for Fable 5.
        out += workingAgreement + "\n"

        // Limitations
        out += "## Limitations (Claude Code)\n\n"
        out += "- **Single level of delegation.** The orchestrator delegates to "
        out += "subagents; subagents cannot delegate further.\n"
        out += "- **No lateral communication.** Subagents do not talk to each other; "
        out += "they only report back to the orchestrator.\n"
        out += "- **Orchestrator model is a launch setting**, documented above — not "
        out += "agent frontmatter.\n"

        return out
    }

    /// Anthropic's tested prompt guidelines for Fable 5, applied repo-wide. These
    /// are widely-recommended best practices; kept verbatim so they aren't watered
    /// down (softer phrasing gets optimized away).
    static let workingAgreement = """
    ## Working agreement (Fable 5 best practices)

    Applies to every agent in this repo.

    - **Scope discipline — no gold-plating.** Don't add features, refactor, or \
    introduce abstractions beyond what the task requires. A bug fix doesn't need \
    surrounding cleanup. Don't design for hypothetical future requirements: do the \
    simplest thing that works well. Only validate at system boundaries.
    - **Act, don't over-plan.** When you have enough information to act, act. Don't \
    re-derive established facts, re-litigate settled decisions, or narrate options \
    you won't pursue — give a recommendation, not a survey.
    - **Grounded progress.** Before reporting progress, audit each claim against a \
    tool result from this session. Only report work you can point to evidence for. \
    If tests fail, say so with the output; if a step was skipped, say that.
    - **Verification beats self-critique.** A fresh-context subagent that saw \
    neither the plan nor the draft verifies the result against the spec. "Done" \
    means a check passed — not that the author is confident.
    - **Never echo internal reasoning** in the response text (it triggers Fable 5's \
    reasoning-extraction safeguard); rely on the structured thinking instead.
    - **Memory.** One lesson per file with a one-line summary; record corrections \
    and confirmed approaches with why they mattered; update existing notes instead \
    of duplicating, and delete notes that turn out to be wrong.

    """

    /// The full managed block, including the start/end markers.
    static func markedBlock(for strategy: Strategy, binary: String = "claude") -> String {
        "\(startMarker)\n\(section(for: strategy, binary: binary))\(endMarker)\n"
    }

    // MARK: - Idempotent merge

    /// Merge the managed block into an existing CLAUDE.md.
    ///
    /// - If `existing` is nil/empty → returns just the managed block.
    /// - If it already contains the markers → replaces everything between them.
    /// - Otherwise → appends the managed block to the end, preserving prior content.
    ///
    /// Running this repeatedly with the same strategy is idempotent.
    static func merged(existing: String?, strategy: Strategy, binary: String = "claude") -> String {
        let block = markedBlock(for: strategy, binary: binary)

        guard let existing, !existing.isEmpty else {
            return block
        }

        if let range = markedRange(in: existing) {
            var result = existing
            result.replaceSubrange(range, with: block.trimmingCharacters(in: .newlines))
            return result
        }

        // Append, ensuring a blank line separator.
        let separator = existing.hasSuffix("\n") ? "\n" : "\n\n"
        return existing + separator + block
    }

    /// The range covering the marked block (inclusive of both markers), or nil.
    /// Recognizes the current markers first, then the legacy ones. The end marker
    /// is searched ONLY after the start, so disordered/duplicated markers (end
    /// before start) yield nil (→ safe append) instead of crashing on an invalid
    /// Range.
    static func markedRange(in text: String) -> Range<String.Index>? {
        range(in: text, start: startMarker, end: endMarker)
            ?? range(in: text, start: legacyStartMarker, end: legacyEndMarker)
    }

    private static func range(in text: String, start startMk: String, end endMk: String) -> Range<String.Index>? {
        guard let start = text.range(of: startMk) else { return nil }
        guard let end = text.range(of: endMk, range: start.upperBound..<text.endIndex) else {
            return nil
        }
        return start.lowerBound..<end.upperBound
    }
}
