//
//  ClaudeMdGenerator.swift
//  StrategyForge
//
//  Generates / updates the repo-root CLAUDE.md. The StrategyForge-owned content
//  lives inside a marked section so an existing CLAUDE.md is never clobbered —
//  only the delimited block is inserted or replaced (idempotent).
//

import Foundation

enum ClaudeMdGenerator {

    static let startMarker = "<!-- CORAL:START -->"
    static let endMarker = "<!-- CORAL:END -->"
    /// Legacy markers from the app's former name. Still recognized when merging so
    /// an already-generated CLAUDE.md gets its block replaced (and upgraded to the
    /// new markers) instead of appending a duplicate.
    static let legacyStartMarker = "<!-- STRATEGYFORGE:START -->"
    static let legacyEndMarker = "<!-- STRATEGYFORGE:END -->"
    static let fileName = "CLAUDE.md"

    // MARK: - Section content

    /// Break any Coral marker that appears inside user-authored content, so a name /
    /// description containing `<!-- CORAL:END -->` can't prematurely close the managed
    /// block and corrupt the next merge.
    static func neutralizeMarkers(_ s: String) -> String {
        s.replacingOccurrences(of: startMarker, with: "<!-- coral start -->")
         .replacingOccurrences(of: endMarker, with: "<!-- coral end -->")
         .replacingOccurrences(of: legacyStartMarker, with: "<!-- sf start -->")
         .replacingOccurrences(of: legacyEndMarker, with: "<!-- sf end -->")
    }

    /// The StrategyForge-managed section (WITHOUT the markers). This is the part
    /// that gets regenerated on every write. `memory` is an optional, pre-rendered
    /// "Learnings from past runs" markdown block (see MemoryDigest); when non-empty it's
    /// appended inside the managed section, so cross-project knowledge rides into the
    /// team's CLAUDE.md. Empty (the default) keeps output byte-identical to before.
    static func section(for strategy: Strategy, binary: String = "claude", memory: String = "") -> String {
        let orchestrator = strategy.orchestrator
        let orchestratorName = orchestrator?.name ?? "orchestrator"
        let orchestratorModel = orchestrator?.model.displayName ?? "—"
        let orchestratorModelID = orchestrator?.model.rawValue ?? "—"

        var out = ""
        out += "# Multi-agent strategy: \(strategy.name)\n\n"
        out += "\(strategy.description)\n\n"
        out += "> Generated by Coral. This section is managed automatically; "
        out += "edit outside the markers to keep your changes.\n\n"

        // Orchestrator
        out += "## Orchestrator\n\n"
        out += "The orchestrator is the **main Claude Code session** (`\(orchestratorName)`). "
        out += "Its model is **not** set in a file — it is chosen at launch.\n\n"
        out += "- Suggested model: **\(orchestratorModel)** (`\(orchestratorModelID)`)\n\n"
        out += "\(LaunchCommandGenerator.instructions(for: strategy, binary: binary))\n\n"

        // Orchestration instructions
        out += "## How to orchestrate\n\n"
        out += "\(strategy.orchestrationNotes)\n\n"

        // Available skills — playbooks in .claude/skills the agents can pull in.
        if !strategy.skills.isEmpty {
            out += "## Available skills\n\n"
            out += "These Agent Skills live in `.claude/skills/` and are pulled into context "
            out += "automatically when a task matches. Use them instead of improvising:\n\n"
            for slug in strategy.skills {
                out += "- `\(slug)` — see `.claude/skills/\(slug)/SKILL.md`.\n"
            }
            out += "\n"
        }

        // Subagents table
        let subagents = strategy.subagentRoles
        if subagents.isEmpty {
            out += "## Subagents\n\n"
            out += "_None — this is a solo configuration with no delegation._\n\n"
        } else {
            out += "## Available subagents\n\n"
            out += "| Subagent | Role | Model | When to use |\n"
            out += "|---|---|---|---|\n"
            var subagentTypes: [String] = []
            for role in subagents {
                let count = max(role.count, 1)
                let nameCell: String
                if count == 1 {
                    nameCell = "`\(role.name)`"
                    subagentTypes.append(role.name)
                } else {
                    nameCell = "`\(role.name)-1`…`\(role.name)-\(count)`"
                    subagentTypes.append(contentsOf: (1...count).map { "\(role.name)-\($0)" })
                }
                let when = role.description
                    .replacingOccurrences(of: "\n", with: " ")
                    .replacingOccurrences(of: "|", with: "\\|")
                out += "| \(nameCell) | \(role.role.displayName) | \(role.model.displayName) | \(when) |\n"
            }
            out += "\n"

            // The delegation is the whole point — and the model will NOT delegate
            // unless told to use the Task tool explicitly. Make it a hard rule and
            // name the exact `subagent_type` values it may call.
            let names = subagentTypes.map { "`\($0)`" }.joined(separator: ", ")
            out += "## Delegate with the Task tool (required)\n\n"
            out += "You are the orchestrator. **Do the work by DELEGATING, not by doing it all yourself.** "
            out += "For anything that fits a subagent above, you MUST call the **Task tool**:\n\n"
            out += "```\nTask(subagent_type: \"\(subagentTypes.first ?? "worker")\", "
            out += "description: \"a precise, self-contained brief with scope + acceptance criteria\")\n```\n\n"
            out += "- Available `subagent_type` values: \(names).\n"
            out += "- When work is parallelizable, launch several subagents **in the same turn** "
            out += "(multiple Task calls at once) so they run concurrently.\n"
            out += "- Give each a complete brief — subagents can't see the conversation, each other, "
            out += "or delegate further.\n"
            out += "- Then collect their reports, integrate, resolve conflicts, and verify.\n"
            out += "- Only skip delegation for trivial one-line answers that need no real work.\n\n"

            out += delegationPlaybook + "\n"
        }

        // Working agreement — Anthropic's tested prompt guidance for Fable 5.
        out += workingAgreement + "\n"

        // Learnings from past runs (cross-project memory), when any apply to this team.
        // Appended before Limitations; neutralizeMarkers below sanitizes its content.
        let mem = memory.trimmingCharacters(in: .whitespacesAndNewlines)
        if !mem.isEmpty { out += mem + "\n\n" }

        // Limitations
        out += "## Limitations (Claude Code)\n\n"
        out += "- **Single level of delegation.** The orchestrator delegates to "
        out += "subagents; subagents cannot delegate further.\n"
        out += "- **No lateral communication.** Subagents do not talk to each other; "
        out += "they only report back to the orchestrator.\n"
        out += "- **Orchestrator model is a launch setting**, documented above — not "
        out += "agent frontmatter.\n"

        // The section is wrapped in CORAL:START/END markers by the merge; make sure the
        // body can never contain a real marker (injected via a name/description/notes).
        return neutralizeMarkers(out)
    }

    /// How to delegate *well* — not just that you must. The Task-tool rule above
    /// makes the orchestrator hand work off; this makes it hand off like a manager
    /// with a capable engineer instead of a micromanager with an intern. The cost of
    /// an agent is dominated by how many turns the lead takes, how much context it
    /// drags along, and what it decides NOT to do itself — so these habits cut cost
    /// and raise quality at the same time.
    static let delegationPlaybook = """
    ## Delegate like a manager, not a micromanager

    The lead's job is judgment — what to build, what to constrain, who writes it —
    not typing the implementation. These habits keep the expensive lead cheap:

    - **Delegate early, not late.** Hand off after a few reconnaissance actions, \
    *before* you pull the important files into your own context and make the design \
    decisions yourself. A late handoff for only the mechanical tail wastes the lead \
    on the expensive work. In practice the lead often never needs to edit code at all.
    - **Brief with constraints, not keystrokes.** Write a spec-quality handoff: \
    enumerate the constraints, edge cases, and an explicit definition of "done" \
    (e.g. "`operator()` must be O(1) in pointer length — NO full token scan"). A \
    constraint you write down can't be forgotten mid-implementation; dictating the \
    implementation line by line can. Specify outcomes, let the subagent choose the how.
    - **Review the diff; don't rewrite it.** When work comes back, a cheap \
    `git diff` / `git show` is usually enough. If you find a bug, prefer another \
    small handoff over pulling the files back and fixing them yourself at lead \
    prices — distrust doesn't increase correctness, it just moves cost up-tier.
    - **Know what NOT to delegate.** Short tasks with nothing between deciding and \
    shipping, and serial debugging where the accumulated context *is* the work, \
    don't decompose — do those yourself. Good delegation is a judgment call, not a \
    quota: the same judgment that writes a good brief also knows when not to write one.

    """

    /// Anthropic's tested prompt guidelines for Fable 5, applied repo-wide. These
    /// are widely-recommended best practices; kept verbatim so they aren't watered
    /// down (softer phrasing gets optimized away).
    static let workingAgreement = """
    ## Working agreement (Fable 5 best practices)

    Applies to every agent in this repo.

    - **Scope discipline — no gold-plating.** Don't add features, refactor, or \
    introduce abstractions beyond what the task requires. A bug fix doesn't need \
    surrounding cleanup. Don't design for hypothetical future requirements: do the \
    simplest thing that works well. Only validate at system boundaries.
    - **Act, don't over-plan.** When you have enough information to act, act. Don't \
    re-derive established facts, re-litigate settled decisions, or narrate options \
    you won't pursue — give a recommendation, not a survey.
    - **Grounded progress.** Before reporting progress, audit each claim against a \
    tool result from this session. Only report work you can point to evidence for. \
    If tests fail, say so with the output; if a step was skipped, say that.
    - **Verification beats self-critique.** A fresh-context subagent that saw \
    neither the plan nor the draft verifies the result against the spec. "Done" \
    means a check passed — not that the author is confident.
    - **Never echo internal reasoning** in the response text (it triggers Fable 5's \
    reasoning-extraction safeguard); rely on the structured thinking instead.
    - **Memory.** One lesson per file with a one-line summary; record corrections \
    and confirmed approaches with why they mattered; update existing notes instead \
    of duplicating, and delete notes that turn out to be wrong.

    """

    /// The full managed block, including the start/end markers.
    static func markedBlock(for strategy: Strategy, binary: String = "claude", memory: String = "") -> String {
        "\(startMarker)\n\(section(for: strategy, binary: binary, memory: memory))\(endMarker)\n"
    }

    // MARK: - Idempotent merge

    /// Merge the managed block into an existing CLAUDE.md.
    ///
    /// - If `existing` is nil/empty → returns just the managed block.
    /// - If it already contains the markers → replaces everything between them.
    /// - Otherwise → appends the managed block to the end, preserving prior content.
    ///
    /// Running this repeatedly with the same strategy is idempotent.
    static func merged(existing: String?, strategy: Strategy, binary: String = "claude", memory: String = "") -> String {
        let block = markedBlock(for: strategy, binary: binary, memory: memory)

        guard let existing, !existing.isEmpty else {
            return block
        }

        if let range = markedRange(in: existing) {
            var result = existing
            result.replaceSubrange(range, with: block.trimmingCharacters(in: .newlines))
            return result
        }

        // Append, ensuring a blank line separator. Any stray marker left behind
        // (a START whose END was deleted by hand or eaten by a merge conflict) is
        // neutralized first: otherwise the NEXT merge would pair the stray START
        // with the appended block's END and wipe the user's content in between.
        var base = existing
        for marker in [startMarker, endMarker, legacyStartMarker, legacyEndMarker]
        where base.contains(marker) {
            base = base.replacingOccurrences(
                of: marker,
                with: marker.replacingOccurrences(of: " -->", with: " (stray) -->"))
        }
        let separator = base.hasSuffix("\n") ? "\n" : "\n\n"
        return base + separator + block
    }

    /// The range covering the marked block (inclusive of both markers), or nil.
    /// Recognizes the current markers first, then the legacy ones. The end marker
    /// is searched ONLY after the start, so disordered/duplicated markers (end
    /// before start) yield nil (→ safe append) instead of crashing on an invalid
    /// Range.
    static func markedRange(in text: String) -> Range<String.Index>? {
        range(in: text, start: startMarker, end: endMarker)
            ?? range(in: text, start: legacyStartMarker, end: legacyEndMarker)
    }

    private static func range(in text: String, start startMk: String, end endMk: String) -> Range<String.Index>? {
        guard let start = text.range(of: startMk) else { return nil }
        guard let end = text.range(of: endMk, range: start.upperBound..<text.endIndex) else {
            return nil
        }
        return start.lowerBound..<end.upperBound
    }
}
