//
//  MissionReport.swift
//  StrategyForge
//
//  Assembles a shareable "mission report" from a finished run using data the app
//  already tracks (the activity timeline, tokens, cost, the team). The headline —
//  "my 4-agent team did X for $0.83" — is the shareable hook of the discovery phase.
//  Pure and testable; the view just renders + exports what this produces.
//

import Foundation

enum MissionReport {

    /// Per-agent summary line for the report table.
    struct AgentLine: Equatable {
        let name: String
        let role: String
        let model: String
        let steps: Int
        let span: String   // "" when it didn't span measurable time
    }

    /// A one-line, shareable headline: "A 4-agent team finished for $0.83."
    static func headline(agentCount: Int, costUSD: Double, tokens: Int) -> String {
        let cost = costUSD > 0 ? String(format: "$%.2f", costUSD) : formatTokens(tokens) + " tokens"
        if agentCount <= 1 { return "A single agent finished for \(cost)." }
        return "A \(agentCount)-agent team finished for \(cost)."
    }

    /// Derive per-agent lines from the strategy + the run's timeline (orchestrator
    /// owns the un-delegated steps; subagents match loosely by name).
    static func agentLines(strategy: Strategy, timeline: [ActivityStep]) -> [AgentLine] {
        func titleCase(_ s: String) -> String {
            s.replacingOccurrences(of: "-", with: " ")
                .split(separator: " ").map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined(separator: " ")
        }
        func stats(matching predicate: (ActivityStep) -> Bool) -> (Int, String) {
            let steps = timeline.filter { !$0.isDelegation && predicate($0) }
            guard let first = steps.first?.at, let last = steps.last?.at else { return (steps.count, "") }
            let span = last.timeIntervalSince(first) >= 1 ? activityElapsed(from: first, to: last) : ""
            return (steps.count, span)
        }

        var lines: [AgentLine] = []
        if let orch = strategy.orchestrator {
            let (n, span) = stats { $0.agent == nil }
            lines.append(AgentLine(name: titleCase(orch.name), role: orch.role.displayName,
                                   model: orch.modelDisplayName, steps: n, span: span))
        }
        for role in strategy.subagentRoles {
            let name = titleCase(role.name)
            let (n, span) = stats { AgentNameMatcher.titlesMatch($0.agent ?? "", name) }
            lines.append(AgentLine(name: name, role: role.role.displayName,
                                   model: role.modelDisplayName, steps: n, span: span))
        }
        return lines
    }

    /// The full Markdown report.
    static func markdown(title: String, strategyName: String, agents: [AgentLine],
                        tokens: Int, costUSD: Double, elapsed: String, outcome: String) -> String {
        let acted = agents.filter { $0.steps > 0 }
        let count = max(acted.count, agents.count)
        var out = "# Mission report — \(title.isEmpty ? strategyName : title)\n\n"
        out += "> \(headline(agentCount: count, costUSD: costUSD, tokens: tokens))\n\n"
        out += "**Team:** \(strategyName) · \(agents.count) agents  \n"
        out += "**Cost:** \(costUSD > 0 ? String(format: "$%.2f", costUSD) : "—") · "
        out += "**Tokens:** \(formatTokens(tokens))"
        if !elapsed.isEmpty { out += " · **Time:** \(elapsed)" }
        out += "\n\n## Agents\n\n"
        out += "| Agent | Role | Model | Steps | Time |\n| --- | --- | --- | ---: | ---: |\n"
        for a in agents {
            out += "| \(a.name) | \(a.role) | \(a.model) | \(a.steps) | \(a.span.isEmpty ? "—" : a.span) |\n"
        }
        let trimmed = outcome.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty {
            let capped = trimmed.count > 1200 ? String(trimmed.prefix(1200)) + "…" : trimmed
            out += "\n## Outcome\n\n\(capped)\n"
        }
        out += "\n---\n*Generated by Coral.*\n"
        return out
    }

    private static func formatTokens(_ n: Int) -> String {
        if n >= 1_000_000 { return String(format: "%.1fM", Double(n) / 1_000_000) }
        if n >= 1_000 { return String(format: "%.1fk", Double(n) / 1_000) }
        return "\(n)"
    }
}
