//
//  StandaloneBriefGenerator.swift
//  StrategyForge
//
//  Builds a single self-contained Markdown "brief" of a strategy for the beginner
//  path: drop it into a plain Claude chat (the Claude app / claude.ai) and Claude
//  acts as the orchestrated team — no repo, Terminal, or Claude Code setup needed.
//
//  (This is a prompt/brief, not the real file-based subagents. In a plain chat
//  there is one model; it *plays* the orchestrated strategy. The real multi-agent
//  version is the generated .claude/agents files used by Claude Code.)
//

import Foundation

enum StandaloneBriefGenerator {

    /// A short prompt the user can paste to kick things off.
    static func starterPrompt(for strategy: Strategy) -> String {
        let orch = strategy.orchestrator
        let team = strategy.subagentRoles
            .map { "\($0.count > 1 ? "\($0.count)× " : "")\($0.name)" }
            .joined(separator: ", ")
        let teamLine = team.isEmpty ? "You work solo." :
            "Act as the orchestrator coordinating these specialists (one level of "
            + "delegation — they report back to you and never talk to each other): \(team)."
        return """
        Act as the multi-agent team described in the attached brief to tackle my task. \
        You are the "\(orch?.name ?? "orchestrator")" (team lead). \(teamLine) \
        Follow the working agreement in the brief. Ask me for my task when ready.
        """
    }

    /// The full self-contained brief.
    static func brief(for strategy: Strategy) -> String {
        var out = "# \(strategy.name) — a multi-agent strategy for Claude\n\n"
        out += "\(strategy.description)\n\n"
        out += "> **How to use this:** paste or drag this file into a Claude chat, "
        out += "then describe your task. Claude will act as the team below. This is a "
        out += "single level of delegation — the specialists report back to the "
        out += "orchestrator and never talk to each other.\n\n"

        out += "## Your task\n\n_Describe what you want done here._\n\n"

        // Orchestrator
        if let orch = strategy.orchestrator {
            out += "## You are: \(orch.name) — the orchestrator (\(orch.model.displayName))\n\n"
            out += "\(orch.systemPrompt.trimmingCharacters(in: .whitespacesAndNewlines))\n\n"
        }

        // Team
        let subs = strategy.subagentRoles
        if !subs.isEmpty {
            out += "## Your team\n\n"
            out += "Delegate each piece to the right specialist, collect their results, "
            out += "and integrate. Specialists do not delegate further or talk to each other.\n\n"
            for role in subs {
                let times = role.count > 1 ? " ×\(role.count)" : ""
                out += "### \(role.name)\(times) — \(role.model.displayName)\n\n"
                out += "_When to use: \(role.description)_\n\n"
                out += "\(role.systemPrompt.trimmingCharacters(in: .whitespacesAndNewlines))\n\n"
            }
        }

        // How to run
        out += "## How to run it\n\n\(strategy.orchestrationNotes)\n\n"

        // Working agreement (shared best practices)
        out += ClaudeMdGenerator.workingAgreement + "\n"

        out += "---\n\n_Generated by StrategyForge._\n"
        return out
    }

    /// A filesystem-safe file name for the brief.
    static func fileName(for strategy: Strategy) -> String {
        let slug = strategy.name
            .lowercased()
            .replacingOccurrences(of: " ", with: "-")
            .filter { $0.isLetter || $0.isNumber || $0 == "-" }
        return "\(slug.isEmpty ? "strategy" : slug)-strategy.md"
    }
}
